name: Easy Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - run: ls
      - run: pip install -r ./requirements-dev.txt
      - run: pytest